#!/usr/bin/env python3
"""
Auto-generated protocol definitions for FGR ESP32 control interface.

This module is generated from the C protocol header file.
Do not edit this file directly - edit the .h file and regenerate.
"""

import struct
from enum import IntEnum
from typing import Optional, Union, Tuple, Any, Dict
import socket

FGR_PROTOCOL_VERSION = 1
FGR_MSG_CONTENTS_MAX_LEN = 256
FGR_LOG_STRING_MAX_LEN = 255

class FGRMsgType(IntEnum):
    """Message types"""
    FGR_MSG_TYPE_NULL = 0
    FGR_MSG_TYPE_REQ = 1
    FGR_MSG_TYPE_CNF = 2
    FGR_MSG_TYPE_IND = 3
    FGR_MSG_TYPE_RSP = 4
    FGR_MSG_TYPE_LOG = 5

class FGRReqCnf(IntEnum):
    """Request/Confirmation message types"""
    FGR_REQ_CNF_NULL = 0
    FGR_REQ_CNF_CFG = 1
    FGR_REQ_CNF_START = 2
    FGR_REQ_CNF_STOP = 3
    FGR_REQ_CNF_LOG_LEVEL = 4
    FGR_REQ_CNF_LOG_START = 5
    FGR_REQ_CNF_LOG_STOP = 6
    FGR_REQ_CNF_REBOOT = 7
    FGR_REQ_CNF_LAST = 31

class FGRIndRsp(IntEnum):
    """Indication/Response message types"""
    FGR_IND_RSP_NULL = 0
    FGR_IND_RSP_NEEDS_CFG = 1
    FGR_IND_RSP_START = 2
    FGR_IND_RSP_STOP = 3
    FGR_IND_RSP_LAST = 31

class FGRLogLevel(IntEnum):
    """Log levels"""
    FGR_LOG_LEVEL_DEBUG = 0
    FGR_LOG_LEVEL_INFO = 1
    FGR_LOG_LEVEL_WARN = 2
    FGR_LOG_LEVEL_ERROR = 3

class FGRError(IntEnum):
    """Error codes"""
    FGR_ERROR_NONE = 0
    FGR_ERROR_GENERIC = 1
    FGR_ERROR_INVALID_REQUEST = 2
    FGR_ERROR_UNHANDLED_REQEST = 3
    FGR_ERROR_INVALID_PARAM = 4
    FGR_ERROR_MSG_TOO_LONG = 5
    FGR_ERROR_ABORTED = 6
    FGR_ERROR_BUSY = 7
    FGR_ERROR_TIMEOUT = 8
    FGR_ERROR_OUT_OF_RESOURCES = 9
    FGR_ERROR_HARDWARE = 10

class FGRState(IntEnum):
    """Device states"""
    FGR_STATE_NOT_POPULATED = 0
    FGR_STATE_NEEDS_CFG = 1
    FGR_STATE_STARTED = 2
    FGR_STATE_STOPPED = 3
    FGR_STATE_BUSY = 4
    FGR_STATE_GENERIC_FAILED = 5
    FGR_STATE_HARDWARE_FAILURE = 6
    FGR_STATE_LAST = 31

class FGRMsgHeader:
    """Message header union - represents all header types"""

    def __init__(self):
        self._header = 0

    @property
    def raw(self) -> int:
        """Get raw header value"""
        return self._header

    @raw.setter
    def raw(self, value: int):
        """Set raw header value"""
        self._header = value

    # Request header accessors
    @property
    def req_type(self) -> int:
        """Get request type (top 12 bits are type, top 4 bits are message type)"""
        return self._header & 0x0FFF

    @req_type.setter
    def req_type(self, value: int):
        msg_type = (self._header >> 12) & 0x0F
        self._header = (msg_type << 12) | (value & 0x0FFF)

    @property
    def req_reference(self) -> int:
        """Get request reference (bits 8-15 of the raw header)"""
        return (self._header >> 8) & 0xFF

    @req_reference.setter
    def req_reference(self, value: int):
        self._header = (self._header & 0xFFFF00FF) | ((value & 0xFF) << 8)

    # Confirmation header accessors
    @property
    def cnf_type(self) -> int:
        """Get confirmation type"""
        return self._header & 0x0FFF

    @cnf_type.setter
    def cnf_type(self, value: int):
        msg_type = (self._header >> 12) & 0x0F
        self._header = (msg_type << 12) | (value & 0x0FFF)

    @property
    def cnf_reference(self) -> int:
        """Get confirmation reference"""
        return (self._header >> 8) & 0xFF

    @cnf_reference.setter
    def cnf_reference(self, value: int):
        self._header = (self._header & 0xFFFF00FF) | ((value & 0xFF) << 8)

    @property
    def cnf_error(self) -> int:
        """Get confirmation error"""
        return (self._header >> 16) & 0xFF

    @cnf_error.setter
    def cnf_error(self, value: int):
        self._header = (self._header & 0xFF00FFFF) | ((value & 0xFF) << 16)

    # Indication header accessors
    @property
    def ind_type(self) -> int:
        """Get indication type"""
        return self._header & 0x0FFF

    @ind_type.setter
    def ind_type(self, value: int):
        msg_type = (self._header >> 12) & 0x0F
        self._header = (msg_type << 12) | (value & 0x0FFF)

    @property
    def ind_reference(self) -> int:
        """Get indication reference"""
        return (self._header >> 8) & 0xFF

    @ind_reference.setter
    def ind_reference(self, value: int):
        self._header = (self._header & 0xFFFF00FF) | ((value & 0xFF) << 8)

    @property
    def ind_state(self) -> int:
        """Get indication state"""
        return (self._header >> 16) & 0xFF

    @ind_state.setter
    def ind_state(self, value: int):
        self._header = (self._header & 0xFF00FFFF) | ((value & 0xFF) << 16)

    # Response header accessors
    @property
    def rsp_type(self) -> int:
        """Get response type"""
        return self._header & 0x0FFF

    @rsp_type.setter
    def rsp_type(self, value: int):
        msg_type = (self._header >> 12) & 0x0F
        self._header = (msg_type << 12) | (value & 0x0FFF)

    @property
    def rsp_reference(self) -> int:
        """Get response reference"""
        return (self._header >> 8) & 0xFF

    @rsp_reference.setter
    def rsp_reference(self, value: int):
        self._header = (self._header & 0xFFFF00FF) | ((value & 0xFF) << 8)

    # Log header accessors
    @property
    def log_level(self) -> int:
        """Get log level"""
        return (self._header >> 8) & 0xFF

    @log_level.setter
    def log_level(self, value: int):
        self._header = (self._header & 0xFFFF00FF) | ((value & 0xFF) << 8)

    def pack(self) -> bytes:
        """Pack header into bytes"""
        return struct.pack("<I", self._header)

    @classmethod
    def unpack(cls, data: bytes) -> "FGRMsgHeader":
        """Unpack bytes into header"""
        header = cls()
        header.raw = struct.unpack("<I", data)[0]
        return header

    def get_message_type(self) -> int:
        """Get the message type from the top 4 bits"""
        return (self._header >> 12) & 0x0F

    def __repr__(self):
        return f"<FGRMsgHeader raw=0x{self._header:08X}>"


class FGRMsg:
    """Main FGR message class with variable-length body"""
    CONTENTS_MAX_LEN = 256

    def __init__(self, msg_type: int = 0, msg_subtype: int = 0,
                 reference: int = 0, error_or_state: int = 0,
                 contents: bytes = b""):
        """Create a new FGR message"""
        self.header = FGRMsgHeader()
        self.contents = contents
        self._set_header_fields(msg_type, msg_subtype, reference, error_or_state)

    def _set_header_fields(self, msg_type: int, msg_subtype: int,
                           reference: int, error_or_state: int):
        """Set header fields based on message type"""
        raw_header = (msg_type << 12) | (msg_subtype & 0x0FFF)
        raw_header |= (reference & 0xFF) << 8
        if msg_type in [2, 3]:  # CNF or IND
            raw_header |= (error_or_state & 0xFF) << 16
        self.header.raw = raw_header

    @classmethod
    def create_req(cls, req_type: int, reference: int = 0,
                   contents: bytes = b"") -> "FGRMsg":
        """Create a request message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_REQ, req_type, reference, 0, contents)

    @classmethod
    def create_cnf(cls, cnf_type: int, reference: int = 0,
                   error: int = 0, contents: bytes = b"") -> "FGRMsg":
        """Create a confirmation message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_CNF, cnf_type, reference, error, contents)

    @classmethod
    def create_ind(cls, ind_type: int, reference: int = 0,
                   state: int = 0, contents: bytes = b"") -> "FGRMsg":
        """Create an indication message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_IND, ind_type, reference, state, contents)

    @classmethod
    def create_rsp(cls, rsp_type: int, reference: int = 0,
                   contents: bytes = b"") -> "FGRMsg":
        """Create a response message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_RSP, rsp_type, reference, 0, contents)

    @classmethod
    def create_log(cls, level: int, message: str = "") -> "FGRMsg":
        """Create a log message"""
        msg = cls(FGRMsgType.FGR_MSG_TYPE_LOG, 0, 0, 0, b"")
        msg.header.log_level = level
        # Encode message without null terminator
        msg.contents = message.encode("utf-8")[:FGR_LOG_STRING_MAX_LEN]
        return msg

    @property
    def message_type(self) -> int:
        """Get the message type"""
        return self.header.get_message_type()

    @property
    def subtype(self) -> int:
        """Get the message subtype (request/indication type, etc.)"""
        return self.header.raw & 0x0FFF

    @property
    def reference(self) -> int:
        """Get the reference field"""
        return (self.header.raw >> 8) & 0xFF

    @property
    def error_or_state(self) -> int:
        """Get error (for CNF) or state (for IND) field"""
        return (self.header.raw >> 16) & 0xFF

    def pack(self) -> bytes:
        """Pack message into bytes for transmission"""
        # Pack header
        header_bytes = self.header.pack()
        # Pack body (length + contents)
        content_length = len(self.contents)
        if content_length > self.CONTENTS_MAX_LEN:
            raise ValueError(f"Contents too long: {content_length} > {self.CONTENTS_MAX_LEN}")
        body_bytes = struct.pack("<I", content_length) + self.contents
        return header_bytes + body_bytes

    @classmethod
    def unpack(cls, data: bytes) -> "FGRMsg":
        """Unpack bytes into a message instance"""
        if len(data) < 4:  # At least header
            raise ValueError(f"Message too short: {len(data)} bytes")
        
        # Unpack header
        header = FGRMsgHeader.unpack(data[:4])
        
        # Unpack body
        if len(data) < 8:
            raise ValueError(f"Message too short for body length: {len(data)} bytes")
        content_length = struct.unpack("<I", data[4:8])[0]
        
        if content_length > 0:
            if len(data) < 8 + content_length:
                raise ValueError(f"Message truncated: expected {8 + content_length} bytes, got {len(data)}")
            contents = data[8:8 + content_length]
        else:
            contents = b""
        
        msg = cls()
        msg.header = header
        msg.contents = contents
        return msg

    def get_log_message(self) -> str:
        """Extract log message from contents (for LOG messages)"""
        if self.message_type != FGRMsgType.FGR_MSG_TYPE_LOG:
            return ""
        return self.contents.decode("utf-8", errors="replace")

    def __repr__(self):
        msg_type_names = {v: k for k, v in FGRMsgType.__members__.items()}
        msg_type_name = msg_type_names.get(self.message_type, "UNKNOWN")
        return f"<FGRMsg type={msg_type_name} subtype=0x{self.subtype:03X} ref={self.reference} contents_len={len(self.contents)}>"

def send_message(sock: socket.socket, msg: FGRMsg) -> bool:
    """Send a protocol message over a socket"""
    try:
        data = msg.pack()
        sock.sendall(data)
        return True
    except Exception as e:
        print(f"Error sending message: {e}")
        return False

def receive_message(sock: socket.socket, timeout: Optional[float] = None) -> Optional[FGRMsg]:
    """Receive and unpack a message (reads length from header)"""
    original_timeout = sock.gettimeout()
    try:
        if timeout is not None:
            sock.settimeout(timeout)
        
        # Read header (4 bytes)
        header_data = sock.recv(4)
        if len(header_data) == 0:
            return None  # Connection closed
        if len(header_data) != 4:
            raise ValueError(f"Incomplete header: got {len(header_data)} bytes")
        
        # Read body length (4 bytes)
        length_data = sock.recv(4)
        if len(length_data) != 4:
            raise ValueError(f"Incomplete length field: got {len(length_data)} bytes")
        content_length = struct.unpack("<I", length_data)[0]
        
        # Read contents
        contents = b""
        if content_length > 0:
            contents = sock.recv(content_length)
            if len(contents) != content_length:
                raise ValueError(f"Incomplete contents: expected {content_length}, got {len(contents)}")
        
        # Reconstruct full message
        full_data = header_data + length_data + contents
        return FGRMsg.unpack(full_data)
    except socket.timeout:
        return None
    except Exception as e:
        print(f"Error receiving message: {e}")
        return None
    finally:
        sock.settimeout(original_timeout)

def create_log_message(level: int, message: str) -> FGRMsg:
    """Convenience function to create a log message"""
    return FGRMsg.create_log(level, message)

def create_config_message(device_type: int, config_data: bytes, reference: int = 0) -> FGRMsg:
    """Create a configuration request message"""
    return FGRMsg.create_req(FGRReqCnf.FGR_REQ_CNF_CFG, reference, config_data)
