#!/usr/bin/env python3
"""
Auto-generated protocol definitions for FGR ESP32 control interface.

This module is generated from the C protocol header file.
Do not edit this file directly - edit the .h file and regenerate.

Note: All multi-byte fields are in network byte order (big-endian)
on the wire. The pack() and unpack() methods handle conversion.
"""

import struct
from enum import IntEnum
from typing import Optional, Union, Tuple, Any, Dict
import socket

FGR_PROTOCOL_VERSION = 1
FGR_MSG_CONTENTS_MAX_LEN = 1024
FGR_LOG_STRING_MAX_LEN = 1023

class FGRMsgType(IntEnum):
    """Message types (top 4 bits of type field)"""
    FGR_MSG_TYPE_NULL = 0
    FGR_MSG_TYPE_REQ = 1
    FGR_MSG_TYPE_CNF = 2
    FGR_MSG_TYPE_IND = 3
    FGR_MSG_TYPE_RSP = 4
    FGR_MSG_TYPE_LOG = 5

class FGRReqCnf(IntEnum):
    """Request/Confirmation message types"""
    FGR_REQ_CNF_NULL = 0
    FGR_REQ_CNF_CFG = 1
    FGR_REQ_CNF_START = 2
    FGR_REQ_CNF_STOP = 3
    FGR_REQ_CNF_LOG_LEVEL = 4
    FGR_REQ_CNF_LOG_START = 5
    FGR_REQ_CNF_LOG_STOP = 6
    FGR_REQ_CNF_LOG_STATUS = 7
    FGR_REQ_CNF_DEBUG_LED_OFF = 8
    FGR_REQ_CNF_DEBUG_LED_ON = 9
    FGR_REQ_CNF_DEBUG_LED_BREATHE_OFF = 10
    FGR_REQ_CNF_DEBUG_LED_BREATHE_ON = 11
    FGR_REQ_CNF_DEBUG_LED_STATUS = 12
    FGR_REQ_CNF_REBOOT = 13
    FGR_REQ_CNF_PING = 14
    FGR_REQ_CNF_LAST = 256

class FGRIndRsp(IntEnum):
    """Indication/Response message types"""
    FGR_IND_RSP_NULL = 0
    FGR_IND_RSP_NEEDS_CFG = 1
    FGR_IND_RSP_START = 2
    FGR_IND_RSP_STOP = 3
    FGR_IND_RSP_HEARTBEAT = 4
    FGR_IND_RSP_LAST = 256

class FGRLogLevel(IntEnum):
    """Log levels"""
    FGR_LOG_LEVEL_DEBUG = 0
    FGR_LOG_LEVEL_INFO = 1
    FGR_LOG_LEVEL_WARN = 2
    FGR_LOG_LEVEL_ERROR = 3

class FGRError(IntEnum):
    """Error codes"""
    FGR_ERROR_NONE = 0
    FGR_ERROR_GENERIC = 1
    FGR_ERROR_INVALID_REQUEST = 2
    FGR_ERROR_UNHANDLED_REQUEST = 3
    FGR_ERROR_INVALID_PARAM = 4
    FGR_ERROR_MSG_TOO_LONG = 5
    FGR_ERROR_ABORTED = 6
    FGR_ERROR_BUSY = 7
    FGR_ERROR_TIMEOUT = 8
    FGR_ERROR_OUT_OF_RESOURCES = 9
    FGR_ERROR_HARDWARE = 10

class FGRState(IntEnum):
    """Device states"""
    FGR_STATE_NOT_POPULATED = 0
    FGR_STATE_NEEDS_CFG = 1
    FGR_STATE_STARTED = 2
    FGR_STATE_STOPPED = 3
    FGR_STATE_BUSY = 4
    FGR_STATE_GENERIC_FAILED = 5
    FGR_STATE_HARDWARE_FAILURE = 6
    FGR_STATE_LAST = 127

class FGRMsgHeader:
    """
    Message header - 4 bytes in network byte order (big-endian)
    
    Layout on wire:
      - Bytes 0-1: type (top 4 bits = message type, bottom 12 bits = subtype)
      - Byte 2: reference
      - Byte 3: for CNF: error, for IND: state, else 0
    """

    def __init__(self):
        self._type: int = 0
        self._reference: int = 0
        self._error_or_state: int = 0

    @classmethod
    def from_network_bytes(cls, data: bytes) -> "FGRMsgHeader":
        """Create header from network bytes (big-endian)"""
        if len(data) < 4:
            raise ValueError(f"Header too short: {len(data)} bytes")
        header = cls()
        header._type = struct.unpack(">H", data[:2])[0]
        header._reference = data[2]
        header._error_or_state = data[3]
        return header

    def to_network_bytes(self) -> bytes:
        """Convert header to network bytes (big-endian)"""
        return struct.pack(">HBB", self._type & 0xFFFF,
                          self._reference & 0xFF,
                          self._error_or_state & 0xFF)

    @property
    def message_type(self) -> int:
        """Get the message type from the top 4 bits of the type field"""
        return (self._type >> 12) & 0x0F

    @message_type.setter
    def message_type(self, value: int):
        """Set the message type (top 4 bits)"""
        self._type = (self._type & 0x0FFF) | ((value & 0x0F) << 12)

    @property
    def subtype(self) -> int:
        """Get the message subtype (bottom 12 bits of type field)"""
        return self._type & 0x0FFF

    @subtype.setter
    def subtype(self, value: int):
        """Set the message subtype (bottom 12 bits)"""
        self._type = (self._type & 0xF000) | (value & 0x0FFF)

    @property
    def reference(self) -> int:
        """Get the reference field"""
        return self._reference

    @reference.setter
    def reference(self, value: int):
        self._reference = value & 0xFF

    @property
    def error_or_state(self) -> int:
        """Get error (for CNF) or state (for IND) field"""
        return self._error_or_state

    @error_or_state.setter
    def error_or_state(self, value: int):
        self._error_or_state = value & 0xFF

    # Legacy properties for backward compatibility with the union approach
    @property
    def raw(self) -> int:
        """Get raw header value (host order) for compatibility"""
        return (self._type << 16) | (self._reference << 8) | self._error_or_state

    @raw.setter
    def raw(self, value: int):
        """Set raw header value (host order) for compatibility"""
        self._type = (value >> 16) & 0xFFFF
        self._reference = (value >> 8) & 0xFF
        self._error_or_state = value & 0xFF

    # Request header accessors for compatibility
    @property
    def req_type(self) -> int:
        return self.subtype

    @req_type.setter
    def req_type(self, value: int):
        self.subtype = value

    @property
    def req_reference(self) -> int:
        return self.reference

    @req_reference.setter
    def req_reference(self, value: int):
        self.reference = value

    # Confirmation header accessors
    @property
    def cnf_type(self) -> int:
        return self.subtype

    @cnf_type.setter
    def cnf_type(self, value: int):
        self.subtype = value

    @property
    def cnf_reference(self) -> int:
        return self.reference

    @cnf_reference.setter
    def cnf_reference(self, value: int):
        self.reference = value

    @property
    def cnf_error(self) -> int:
        return self.error_or_state

    @cnf_error.setter
    def cnf_error(self, value: int):
        self.error_or_state = value

    # Indication header accessors
    @property
    def ind_type(self) -> int:
        return self.subtype

    @ind_type.setter
    def ind_type(self, value: int):
        self.subtype = value

    @property
    def ind_reference(self) -> int:
        return self.reference

    @ind_reference.setter
    def ind_reference(self, value: int):
        self.reference = value

    @property
    def ind_state(self) -> int:
        return self.error_or_state

    @ind_state.setter
    def ind_state(self, value: int):
        self.error_or_state = value

    # Response header accessors
    @property
    def rsp_type(self) -> int:
        return self.subtype

    @rsp_type.setter
    def rsp_type(self, value: int):
        self.subtype = value

    @property
    def rsp_reference(self) -> int:
        return self.reference

    @rsp_reference.setter
    def rsp_reference(self, value: int):
        self.reference = value

    # Log header accessors
    @property
    def log_level(self) -> int:
        return self.reference

    @log_level.setter
    def log_level(self, value: int):
        self.reference = value

    def pack(self) -> bytes:
        """Pack header into network bytes (big-endian)"""
        return self.to_network_bytes()

    @classmethod
    def unpack(cls, data: bytes) -> "FGRMsgHeader":
        """Unpack network bytes (big-endian) into header"""
        return cls.from_network_bytes(data)

    def get_message_type(self) -> int:
        """Get the message type from the top 4 bits of the type field"""
        return self.message_type

    def __repr__(self):
        return f"<FGRMsgHeader type=0x{self._type:04X} ref={self._reference} err/state={self._error_or_state}>"


class FGRMsg:
    """Main FGR message class with variable-length body"
    All multi-byte fields are in network byte order (big-endian) on the wire"""
    CONTENTS_MAX_LEN = 1024

    def __init__(self, msg_type: int = 0, msg_subtype: int = 0,
                 reference: int = 0, error_or_state: int = 0,
                 contents: bytes = b""):
        """Create a new FGR message"""
        self.header = FGRMsgHeader()
        self.contents = contents
        self._set_header_fields(msg_type, msg_subtype, reference, error_or_state)

    def _set_header_fields(self, msg_type: int, msg_subtype: int,
                           reference: int, error_or_state: int):
        """Set header fields based on message type"""
        self.header.message_type = msg_type
        self.header.subtype = msg_subtype
        self.header.reference = reference
        self.header.error_or_state = error_or_state

    @classmethod
    def create_req(cls, req_type: int, reference: int = 0,
                   contents: bytes = b"") -> "FGRMsg":
        """Create a request message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_REQ, req_type, reference, 0, contents)

    @classmethod
    def create_cnf(cls, cnf_type: int, reference: int = 0,
                   error: int = 0, contents: bytes = b"") -> "FGRMsg":
        """Create a confirmation message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_CNF, cnf_type, reference, error, contents)

    @classmethod
    def create_ind(cls, ind_type: int, reference: int = 0,
                   state: int = 0, contents: bytes = b"") -> "FGRMsg":
        """Create an indication message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_IND, ind_type, reference, state, contents)

    @classmethod
    def create_rsp(cls, rsp_type: int, reference: int = 0,
                   contents: bytes = b"") -> "FGRMsg":
        """Create a response message"""
        return cls(FGRMsgType.FGR_MSG_TYPE_RSP, rsp_type, reference, 0, contents)

    @classmethod
    def create_log(cls, level: int, message: str = "") -> "FGRMsg":
        """Create a log message"""
        msg = cls(FGRMsgType.FGR_MSG_TYPE_LOG, 0, 0, 0, b"")
        msg.header.log_level = level
        # Encode message without null terminator
        msg.contents = message.encode("utf-8")[:FGR_LOG_STRING_MAX_LEN]
        return msg

    @property
    def message_type(self) -> int:
        """Get the message type"""
        return self.header.message_type

    @property
    def subtype(self) -> int:
        """Get the message subtype (request/indication type, etc.)"""
        return self.header.subtype

    @property
    def reference(self) -> int:
        """Get the reference field"""
        return self.header.reference

    @property
    def error_or_state(self) -> int:
        """Get error (for CNF) or state (for IND) field"""
        return self.header.error_or_state

    def pack(self) -> bytes:
        """Pack message into network bytes (big-endian) for transmission"""
        # Pack header
        header_bytes = self.header.pack()
        # Pack body (length in big-endian + contents)
        content_length = len(self.contents)
        if content_length > self.CONTENTS_MAX_LEN:
            raise ValueError(f"Contents too long: {content_length} > {self.CONTENTS_MAX_LEN}")
        body_bytes = struct.pack(">I", content_length) + self.contents
        return header_bytes + body_bytes

    @classmethod
    def unpack(cls, data: bytes) -> "FGRMsg":
        """Unpack network bytes (big-endian) into a message instance"""
        if len(data) < 4:  # At least header
            raise ValueError(f"Message too short: {len(data)} bytes")
        
        # Unpack header
        header = FGRMsgHeader.unpack(data[:4])
        
        # Unpack body
        if len(data) < 8:
            raise ValueError(f"Message too short for body length: {len(data)} bytes")
        content_length = struct.unpack(">I", data[4:8])[0]
        
        if content_length > 0:
            if len(data) < 8 + content_length:
                raise ValueError(f"Message truncated: expected {8 + content_length} bytes, got {len(data)}")
            contents = data[8:8 + content_length]
        else:
            contents = b""
        
        msg = cls()
        msg.header = header
        msg.contents = contents
        return msg

    def get_log_message(self) -> str:
        """Extract log message from contents (for LOG messages)"""
        if self.message_type != FGRMsgType.FGR_MSG_TYPE_LOG:
            return ""
        return self.contents.decode("utf-8", errors="replace")

    def __repr__(self):
        msg_type_names = {v: k for k, v in FGRMsgType.__members__.items()}
        msg_type_name = msg_type_names.get(self.message_type, "UNKNOWN")
        return f"<FGRMsg type={msg_type_name} subtype=0x{self.subtype:03X} ref={self.reference} contents_len={len(self.contents)}>"

def _recv_exact(sock: socket.socket, n: int, timeout: Optional[float] = None) -> Optional[bytes]:
    """Receive exactly n bytes from the socket, or return None on timeout/disconnect."""
    data = b""
    remaining = n
    
    while remaining > 0:
        try:
            chunk = sock.recv(remaining)
            if not chunk:
                return None  # Connection closed
            data += chunk
            remaining -= len(chunk)
        except socket.timeout:
            return None
        except socket.error:
            return None
    
    return data

def send_message(sock: socket.socket, msg: FGRMsg) -> bool:
    """Send a protocol message over a socket (network byte order)"""
    try:
        data = msg.pack()
        sock.sendall(data)
        return True
    except Exception as e:
        print(f"Error sending message: {e}")
        return False

def receive_message(sock: socket.socket, timeout: Optional[float] = None) -> Optional[FGRMsg]:
    """Receive and unpack a message (handles TCP streaming properly).
    
    Reads exactly:
      1. 4 bytes (header)
      2. 4 bytes (length)
      3. length bytes (contents)
    
    Returns None on timeout or connection close.
    """
    original_timeout = sock.gettimeout()
    try:
        if timeout is not None:
            sock.settimeout(timeout)
        
        # Read exactly 4 bytes for header
        header_data = _recv_exact(sock, 4)
        if header_data is None:
            return None
        
        # Read exactly 4 bytes for length
        length_data = _recv_exact(sock, 4)
        if length_data is None:
            return None
        
        content_length = struct.unpack(">I", length_data)[0]
        
        # Validate length to prevent memory issues
        if content_length > FGR_MSG_CONTENTS_MAX_LEN:
            # Protocol error - we may be out of sync
            print(f"Error: Invalid content length {content_length} > {FGR_MSG_CONTENTS_MAX_LEN}")
            return None
        
        # Read exactly content_length bytes
        contents = b""
        if content_length > 0:
            contents = _recv_exact(sock, content_length)
            if contents is None:
                return None
        
        # Reconstruct full message and unpack
        full_data = header_data + length_data + contents
        return FGRMsg.unpack(full_data)
        
    except socket.timeout:
        return None
    except Exception as e:
        print(f"Error receiving message: {e}")
        return None
    finally:
        sock.settimeout(original_timeout)

def create_log_message(level: int, message: str) -> FGRMsg:
    """Convenience function to create a log message"""
    return FGRMsg.create_log(level, message)

def create_config_message(device_type: int, config_data: bytes, reference: int = 0) -> FGRMsg:
    """Create a configuration request message"""
    return FGRMsg.create_req(FGRReqCnf.FGR_REQ_CNF_CFG, reference, config_data)
